### ISSUE TITLE
Problem resolving function overload

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1079]
In builds prior to 2.12, the following function call would resolve to the user defined function and return 123 as expected. From 2.12 onward, the call resolves to the same named function defined in the X# runtime, which accepts a IntPtr and thus fails at runtime with a XSharp.Error:Conversion Error from USUAL (STRING) to PTR

```
FUNCTION Start() AS VOID
LOCAL u AS USUAL
u := "abc"
? FGetFileName(u)
RETURN

FUNCTION FGetFileName(cFullFileName) CLIPPER
RETURN 123
```

**Comment by RobertvanderHulst** [comment]
If the function would have had the same prototype as the function inside XSharp.Core then the function in the current assembly would have been chosen.

**Comment by RobertvanderHulst** [comment]
I have fixed this now but I have also added a warning message:
`warning XS9043: 'FGetFileName' is ambiguous. Could be Method 'R862.Exe.Functions.FGetFileName(params usual[])' in R862 or Method 'XSharp.Core.Functions.FGetFileName(System.IntPtr)' in XSharp.Core. Using the first one.`
This warning will not be shown if the function in the users code has the same prototype.
This should help to avoid accidentally overriding built-in functions.

**Comment by cpyrgas** [comment]
Robert, I think that's a very good idea!

**Comment by cpyrgas** [comment]
Problem fixed when function is defined in the same library as in the calling code, but still happens when it's defined in a referenced library, see C866

**Comment by cpyrgas** [comment]
Confirmed fixed
