### ISSUE TITLE
VOWED problem with the "Type" and "Tab key" properties in DialogWindows

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1227]
Attached simple (Dialog) window in VO has set the options "Type" to "Tab Page" and "Tab key" to "Include Parent".

- After porting this to X# and opening the window in VS, the "Tab key" property is incorrectly set to "Form Only"
- Doing a dummy save to the window, closing it and reopening it, now the property is set to "Include Parent"
- Change it to "Form Only", save, close and reopen, now it's back to "Include Parent"!
- XIDE has the opposite issue, property after a save always resets to "Form Only"

[SimpleGUI.zip](https://github.com/X-Sharp/XSharpPublic/files/10962434/SimpleGUI.zip)

**Comment by christianschmid200272** [comment]
Something seems to have been lost here. The bug was fixed in the test version of XSharp.VoEditor.dll from March 2023, but the change was never integrated into a release during the course of the issue.

**Comment by RobertvanderHulst** [comment]
Christian,
I see that Chris did not check in any code changes. The ticket was also not marked as Closed, or assigned to a project or milestone. I have just done that and will ask Chris to review this again and check-in the changes.

**Comment by cpyrgas** [comment]
Christian, Robert, I had not fixed that issue, it's too complicated and the behavior also in VO is a mess, I'm sure there's some hack hardcoded there about this property and it also "sometimes" works in VO (depends on the state of other properties as well). Christian, in March 2023 I had sent you a fix for another issue, regarding the menu editor, not the window editor. For the "tab key" issue I had sent you a workaround tip, which had worked for you:

> Found the problem, there's some bug in loading the "Tab Key" property of dialog windows in the window editor. Please change it in the window(s) that have this problem from "Form Only" to "Include Parent", save the window again, and now it should work correctly.

I will look into this again to try to properly fix this, but I can't make promises..
