### ISSUE TITLE
DBFCDX: Incorrect index scope visibility immediately after file creation

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1238]
If you create a new DBF file with an index, open it, set SCOPE for the index, fill the file with records that satisfy the SCOPE, and then reread the resulting workarea contents, then only one record has visibility, instead of all created records.
The bug was found in a real application.

**Example:**
```
LOCAL cPath, cFile AS STRING
LOCAL aStruct AS ARRAY

cPath := WorkDir() + "Files\"
cFile := cPath + "FILE1.DBF"

aStruct := {;
	{"COL1", "N", 4, 0, "COL1"};
}

IF File(cFile)
	FErase(cFile)
ENDIF

// Isolated creation
VODBCreate(cFile, aStruct, "DBFCDX", TRUE, "FILE1", NULL, TRUE, FALSE)
DBCreateOrder("FILE1", cPath + "FILE1.CDX", "STR(COL1,4)", {|| STR(_FIELD->COL1, 4)}, FALSE)
VODBCloseArea()

// Open
IF VODBUseArea(TRUE, "DBFCDX", cPath + "FILE1.DBF", "FILE1", TRUE, FALSE)

	LOCAL CONST nScopeVal := 1 AS INT
	LOCAL cS := Str(nScopeVal, 4) AS STRING

	OrdScope(TOPSCOPE, cS)
	OrdScope(BOTTOMSCOPE, cS)
	VODBGoTop()

	TRY

		LOCAL CONST nNumberOfTestRecords := 5 AS INT // any number greater than 1

		// Filling with data
		FOR LOCAL i := 1 AS INT UPTO nNumberOfTestRecords + 1
			VODBAppend(FALSE)
			FieldPutSym(#COL1, nScopeVal)
		NEXT

		VODBCommit()
		VODBUnlock(NIL)

		// Test
		LOCAL nCountInCurrentScope := 0 AS INT
		VODBGoTop()
		DO WHILE !VODBEof()
			nCountInCurrentScope++
			VODBSkip(1)
		ENDDO

		? nCountInCurrentScope // must be <nNumberOfTestRecords + 1>, instead 1
		WAIT

	FINALLY
		VODBCloseArea()
	END TRY

ENDIF
```

**Example project:**
[TestConsoleApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/11170437/TestConsoleApplication.zip)

**Environment:**
X# 2.14.0.4
IDE: VS2019
RDD: DBFCDX

**Comment by RobertvanderHulst** [comment]
This seems to work in 2.18

**Comment by leon-ts** [comment]
Just to note that in X# 2.17.0.3 this bug is still present. Both in real applications and in the test example that I attached in this ticket.

**Comment by RobertvanderHulst** [comment]
I have fixed this in the 2.18 code.

**Comment by cpyrgas** [comment]
Robert, have you checked in the change for the fix? I updated my runtime dlls, but I still see the problem..

**Comment by RobertvanderHulst** [comment]
I committed the change, but did not push it. Did that now

**Comment by cpyrgas** [comment]
Confirmed fixed!
