### ISSUE TITLE
VS editor parameter list tooltip does not show after selecting a method from member completion list

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1570]
In all VS versions, after you select a method from a member completion list, the editor auto-types the opening parentheses, the parameter tip for the chosen method appears for a moment, but then immediately disappears. To reproduce, select for example "CompareTo" from the list in the code below.

I think this was fixed some time ago, but looks like it resurfaced in 2.21

FUNCTION Start() AS VOID
    LOCAL n AS INT
    n:

**Comment by RobertvanderHulst** [comment]
Already fixed with last weeks changes

**Comment by cpyrgas** [comment]
Unfortunately this still happens, in all VS versions. For VS 2022 I have updated it to the latest version 17.11.4

**Comment by RobertvanderHulst** [comment]
With which key are you selecting the entry from the completionlist?

**Comment by cpyrgas** [comment]
Yeap :)

**Comment by cpyrgas** [comment]
Confirmed fixed
