### ISSUE TITLE
OrdDescend() + OrderScope() and Eof()/Bof() problem

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#579]
This sample switches to the descend view before it tries to set a OrderScope 

Note: the sample uses instead of 

OrdScope(TOPSCOPE, "R")     
OrdScope(BOTTOMSCOPE, "B")  

the wrong order:

OrdScope(TOPSCOPE, "B")     // Note: must be "R" !
OrdScope(BOTTOMSCOPE, "R")  // Note: must be "B" !

ordKeycount() returns correctly 0
but Eof() returns .f. instead of .t.
but Bof() returns .f. instead of .t.

```
FUNCTION OrdDescAndOrdScope() AS VOID 
LOCAL cDBF, cPfad, cIndex   AS STRING 
LOCAL aFields, aValues AS ARRAY 
LOCAL i AS DWORD  


    RddSetDefault ( "DBFCDX" ) 
    
    cPfad := "D:\test\" 
 
	cDBF := cPfad + "Foo"
	cIndex := cPfad + "Foox" 
	
	FErase ( cIndex + IndexExt() )
		
	aFields := { { "LAST" , "C" , 20 , 0 } 	} 
	
	aValues := { "g6" , "o2", "g2" , "g1" , "g3" , "g5" , "B1" , "b2" , "p", "q" , "r" , "s" }	
	
	// ------------
	
	DbCreate( cDBF , AFields)
	DbUseArea( ,,cDBF )		

	FOR i := 1 UPTO ALen ( aValues )
		DbAppend() 
		FieldPut ( 1 , aValues [ i ] )
	NEXT
	
	DbCreateOrder ( "ORDER1" , cIndex , "upper(LAST)" , { || Upper ( _Field->LAST) } )
	DbCloseArea()
	
	// --------------
	
	DbUseArea( ,,cDBF )
	DbSetIndex ( cIndex )
	DbSetOrder ( 1 ) 
	
	OrdDescend ( , , TRUE )  // switch to descend view

	OrdScope(TOPSCOPE, "B")     // Note: must be "R" !
	OrdScope(BOTTOMSCOPE, "R")  // Note: must be "B" !
	
	? "OrdKeyCount()" , OrdKeyCount()
	?     
	
	// -------------	
	
	DbGoTop()            
	? Bof() , Eof()  // both return .f. !


    DO WHILE ! Eof()
    	? FieldGet ( 1 ) 
    	DbSkip ( 1 )
    	
    ENDDO 	
           
   
    DbGoTop()       
    ? Bof() , Eof() // both return .f. !
    
    DbGoBottom()       
    ? Bof() , Eof() // both return .f. !


	DbCloseArea() 
	
	RETURN 		 	

```
regards
Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Can't confirm fix, EoF() now correctly returns TRUE, but BoF() still returns FALSE.

**Comment by cpyrgas** [comment]
There still exists a strange problem: When  SetDeleted(TRUE) in the sample of this issue, then the call to OrdKeyCount() returns 1. If SetDeleted(FALSE), then it returns 0 as expected. In VO, regardless the state of SetDeleted(), the result of OrdKeyCount() is always 0.

Found this because in the test suite I had forgotten to reset back SetDeleted() in a previous test.

**Comment by cpyrgas** [comment]
Confirm fixed.
