### ISSUE TITLE
DBFCDX corruption with simultaneous updates

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#585]
- First run program no 1.
- Then run program no 2.
(remember to update the dbf path if needed!)
- Let them run for a minute or so
- At some point, either only one or both the programs will throw the exception mentioned below. A few times there is no exception, but program #1 stops adding records (apparently some deadlock happens?)

No 1:

```
FUNCTION Start() AS VOID
	LOCAL cPath			AS STRING
	LOCAL nI			AS DWORD
	LOCAL nLen			AS DWORD
	LOCAL aValues		AS ARRAY
	LOCAL aStruct AS ARRAY
	LOCAL n AS INT

	cPath			:= "C:\test\Wolfgang"
	FErase(cPath + ".dbf")
	FErase(cPath + ".cdx")
	
	aStruct := {{"AUFNR","N",10,0},{"JAHR","C",4,0},{"POSFORO","N",4,0},{"POSGRUP","N",4,0},{"POSNR","N",4,0}}
	
	? DbCreate(cPath , aStruct , "DBFCDX")

	? DbUseArea(TRUE, "DBFCDX" , cPath, ,FALSE,FALSE)
	? DbCreateIndex(cPath , "JAHR+STR(AUFNR,10)+STR(POSFORO,4)+STR(POSGRUP,4)+STR(POSNR,4)")
	? DbCloseArea()
	
	? DbUseArea(TRUE, "DBFCDX" , cPath, ,TRUE,FALSE)
	DbGoBottom()
	nLen				:= FCount()
	aValues				:= ArrayNew( nLen )
	WHILE TRUE
		TRY
			FOR nI := 1 UPTO nLen
				aValues[nI]			:= FieldGet( nI )
			NEXT
			DbAppend( TRUE )
			n ++
			FOR nI := 1 UPTO nLen
				FieldPut( nI, aValues[nI] )
			NEXT           
			FieldPut( 5, FieldGet( 5 ) + 1 )
			IF FieldGet( 5 ) > 900
				FieldPut( 5, 1 )
				FieldPut( 1, FieldGet( 1 ) + 1 )
			ENDIF
			DbCommit()
			DbUnLock()
		CATCH e AS Exception
			? e:ToString()
		END TRY
		? n
	END

RETURN
```

No 2:

```

FUNCTION Start() AS VOID
	LOCAL cPath AS STRING
	LOCAL n AS INT
	cPath			:= "C:\test\Wolfgang"
	DbUseArea( TRUE, "DBFCDX", cPath, "AUFPOS", TRUE, FALSE )
	TRY
		WHILE TRUE
			n++
			DbGoTop()
				DO WHILE ! Eof()
					IF RLock()
						FieldPut( 3, n )
						DbCommit()
						DbUnLock()
					ENDIF
					DbSkip()
				END
		END
	CATCH e AS Exception
		? e:ToString()
	END TRY
	DbCloseArea()
RETURN

```

Exception:

```
Description :   Error performing action InsertKey for C:\dbf\Wolfgang.CDX WOLFGANG
Subsystem :     DBFCDX
GenCode :       EG_CORRUPTION Corruption detected
SubCode :       1106 Create indexfile
FuncSym :       DbUnLock
Severity :      ES_ERROR
Can Default :   False
Can Retry :     False
Can Substitute :        False
FileName :      C:\dbf\Wolfgang.DBF
Stack Trace :
   at XSharp.RDD.CDX.CdxTag._UpdateError(Exception ex, String strFunction, String strMessage)
   at XSharp.RDD.CDX.CdxTag.DoAction(CdxAction action)
   at XSharp.RDD.CDX.CdxTag._keyUpdate(Int32 recordNo, Boolean lNewRecord)
   at XSharp.RDD.CDX.CdxTag.GoCold()
   at XSharp.RDD.CDX.CdxOrderBag.GoCold()
   at XSharp.RDD.CDX.CdxOrderBagList.GoCold()
   at XSharp.RDD.DBFCDX.GoCold()
   at XSharp.RDD.DBF.UnLock(Object oRecId)
   at XSharp.CoreDb.<>c__DisplayClass110_0.<Unlock>b__0()
   at XSharp.CoreDb.Do[T](Func`1 action)
   at XSharp.CoreDb.Unlock(Object uRecno)
   at XSharp.RT.Functions.DbUnLock()


```

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
There still seems to exist a problem, after letting the 2 programs run for a while (around a minute in my machine), I get this assertion failed dialog:


```

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------

   at XSharp.RDD.CDX.CdxTag._locate(Byte[] keyBuffer, Int32 keyLength, SearchMode searchMode, Int32 pageOffset, Int32 recNo) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg:line 701

   at XSharp.RDD.CDX.CdxTag._locate(Byte[] keyBuffer, Int32 keyLength, SearchMode searchMode, Int32 pageOffset, Int32 recNo) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg:line 780

   at XSharp.RDD.CDX.CdxTag._keyUpdate(Int32 recordNo, Boolean lNewRecord) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagUpdate.prg:line 845

   at XSharp.RDD.CDX.CdxTag.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTag.prg:line 328

   at XSharp.RDD.CDX.CdxOrderBag.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBag.prg:line 338

   at XSharp.RDD.CDX.CdxOrderBagList.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBagList.prg:line 202

   at XSharp.RDD.DBFCDX.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\DbfCdx.prg:line 601

   at XSharp.RDD.CDX.CdxTag.SkipRaw(Int32 nToSkip) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg:line 200

   at XSharp.RDD.DBFCDX.SkipRaw(Int32 move) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\DbfCdx.prg:line 582

   at XSharp.RDD.Workarea.Skip(Int32 nToSkip) in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\Workarea.prg:line 207

   at XSharp.RDD.DBF.Skip(Int32 nToSkip) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg:line 242

   at XSharp.CoreDb.<>c.<Commit>b__30_0() in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 440

   at XSharp.CoreDb.Do[T](Func`1 action) in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 234

   at XSharp.CoreDb.Commit() in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 438

   at XSharp.RT.Functions.DbCommit() in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg:line 255

   at xRuntime.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg:line 40


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by cpyrgas** [comment]
I am afraid the problem still happens, although now it is more rare, it takes much more time to happen in my PC. 

In the first time I run the samples again, after a couple minutes I got an assertion failed dialog, the message looked like the previous one posted here but I did not keep it, will do that and will post it next time it happens.

In my second attempt, the samples run well for 5 minutes or so, but then got a TimeoutException. I will run more tests and report back what I find.


```
System.TimeoutException: Timeout locking file C:\test\Wolfgang.DBF Offset 2147483648 Len 1
   at XSharp.RDD.LockTimer.TimeOut(String cFileName, Int64 nOffSet, Int64 nLen) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\Support.prg:line 101
   at XSharp.RDD.DBF.HeaderLock(DbLockMode lockMode) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg:line 424
   at XSharp.RDD.DBF.Flush() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg:line 1552
   at XSharp.RDD.DBFCDX.Flush() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\DbfCdx.prg:line 626
   at XSharp.CoreDb.<>c.<Commit>b__30_0() in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 442
   at XSharp.CoreDb.Do[T](Func`1 action) in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 234
   at XSharp.CoreDb.Commit() in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 438
   at XSharp.RT.Functions.DbCommit() in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg:line 262

```

**Comment by cpyrgas** [comment]
This is the other callstack:

```

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at XSharp.RDD.CDX.CdxTag._keyUpdate(Int32 recordNo, Boolean lNewRecord) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagUpdate.prg:line 831

   at XSharp.RDD.CDX.CdxTag.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTag.prg:line 332

   at XSharp.RDD.CDX.CdxOrderBag.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBag.prg:line 337

   at XSharp.RDD.CDX.CdxOrderBagList.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBagList.prg:line 202

   at XSharp.RDD.DBFCDX.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\DbfCdx.prg:line 602

   at XSharp.RDD.CDX.CdxTag.SkipRaw(Int32 nToSkip) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg:line 211

   at XSharp.RDD.DBFCDX.SkipRaw(Int32 move) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\DbfCdx.prg:line 583

   at XSharp.RDD.Workarea.Skip(Int32 nToSkip) in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\Workarea.prg:line 207

   at XSharp.RDD.DBF.Skip(Int32 nToSkip) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg:line 242

   at XSharp.CoreDb.<>c.<Commit>b__30_0() in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 440

   at XSharp.CoreDb.Do[T](Func`1 action) in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 234

   at XSharp.CoreDb.Commit() in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 438

   at XSharp.RT.Functions.DbCommit() in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg:line 262

   at RDDTester.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\RDDTester\Prg\Start.prg:line 14


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by cpyrgas** [comment]
And a different one:

```

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------

   at XSharp.RDD.CDX.CdxOrderBag._xLockComix() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBag.prg:line 633

   at XSharp.RDD.CDX.CdxOrderBag.XLock() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBag.prg:line 540

   at XSharp.RDD.CDX.CdxTag.Xlock() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagLock.prg:line 29

   at XSharp.RDD.CDX.CdxTag._keyUpdate(Int32 recordNo, Boolean lNewRecord) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagUpdate.prg:line 777

   at XSharp.RDD.CDX.CdxTag.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTag.prg:line 332

   at XSharp.RDD.CDX.CdxOrderBag.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBag.prg:line 337

   at XSharp.RDD.CDX.CdxOrderBagList.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\CdxOrderBagList.prg:line 202

   at XSharp.RDD.DBFCDX.GoCold() in C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\DbfCdx.prg:line 602

   at XSharp.RDD.DBF.Append(Boolean lReleaseLock) in C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg:line 335

   at XSharp.CoreDb.<>c__DisplayClass18_0.<Append>b__0() in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 276

   at XSharp.CoreDb.Do[T](Func`1 action) in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 234

   at XSharp.CoreDb.Append(Boolean lReleaseLocks) in C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 274

   at XSharp.RT.Functions.DbAppend(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Db.prg:line 274

   at xRuntime.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg:line 119


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by cpyrgas** [comment]
Some times I get this one, hope one of those callstacks do help:

Description :	Exception of type 'XSharp.RDD.RddError' was thrown.
Subsystem :	DBFCDX
GenCode :	EG_CORRUPTION Corruption detected
SubCode :	1002 Invalid order specification
FuncSym :	DbSkip
Severity :	ES_ERROR
Can Default :	True
Can Retry :	False
Can Substitute :	False
FileName :	C:\test\Wolfgang.DBF
Stack Trace :	
RDDERROR:.CTOR (Line: 25)
DBF:_DBFERROR (Line: 1397)
DBF:_DBFERROR (Line: 1389)
CDXTAG:THROWEXCEPTION (Line: 41)
CDXTAG:_GETNEXTKEY (Line: 314)
CDXTAG:_NEXTKEY (Line: 638)
CDXTAG:SKIPRAW (Line: 256)
DBFCDX:SKIPRAW (Line: 583)
DBF:SKIP (Line: 244)
COREDB:<>C__DISPLAYCLASS104_0:<SKIP>B__0 (Line: 1901)
COREDB:DO (Line: 234)
COREDB:SKIP (Line: 1898)
DBSKIP (Line: 661)
START (Line: 17)

**Comment by RobertvanderHulst** [comment]
Chris,
I am afraid those callstacks only reveal when the RDD (read Robert) detects an unexpected situation. But then it is already too late. For example the _getNextKey() (the last one) happens when:
- the RDD is skipping to the next node on a page
- when we are at the end of the page (the current node is the last node on the page) then we use the pointer to the right sibling page to find the next page at that level, so we can return its first node . 

This was a place where I detected problems. So (for now) I have added code in the RDD that looks at the pointers to the left and right siblings, reads these pages and compares the "boundary" nodes: the last node on the left sibling should precede the first node on the current page and the first node on the right sibling should follow the last node on the current page. With "node" I mean Key + Recno: when there are duplicate keys then the nodes on a page are sorted in record number order.
So the only thing this shows is that there is a problem but not what caused the problem.

The timeout on the DBF means that the other process has locked the header of the file for more than 30 seconds. That indicates that the other program is "hanging". Could it be that the other process was displaying an assertion error at that time ?

The assertion error for the _keyupdate is something else (but also indicates corruption): after seeking for a key then the "page stack" which contains the pages that were visited should contain 0 or more branch pages, and exactly one leaf page. This assertion tells us that the leaf page is missing. That is not good...

The assertion error inside _xLockComix also indicates a strange situation: we work with so called "shared locks" and "exclusive locks". Shared locks are used to prevent other workstations from updating the file while we are reading. When we do a gotop, skip, gobottom or seek then we read multiple pages from the index. We do not want others to change these pages, but it is no problem if other read pages as well. A Shared lock prevents others from getting an exclusive lock, which is needed to update the index.
Normally you do not ask for an Exclusive lock when you are holding a shared lock. This assertion tells us (me) that there is a situation where this happens. This is strange, because all locking happens inside try .. finally statements, and inside the finally block the RDD should always unlock a previous set lock. Apparently there is a situation where (maybe because of another problem) this does not happen.

These assertion will not be visible in a release version of the RDD. But I think I will need to spend more time (again) to find the final issue(s) that are triggering these error messages and exceptions.

Btw: I think I will NOT delay the next build because of this.

**Comment by cpyrgas** [comment]
Robert,
OK, I can only imagine how much complicated and difficult it is to find the root cause of this. The new build already contains a lot of other improvements and fixes, this can always be released as a hotfix afterwards.

The timeout error only appeared once in my tests, I remember seeing that both apps had stalled at the moment. I do not remember getting an assertion dialog shown in one of them, but possibly I just missed it. Will report back if I see this error again.

Just for completeness, I run the same apps also in VO just in case, but they both seem to execute well.

**Comment by cpyrgas** [comment]
Unfortunately the corruption still happens, usually within a minute of running the two samples.
There are no random numbers used in those samples, they are both linear, but of course since they are running simultaneously, the order in which appends and updates happen is not the same every time.

**Comment by cpyrgas** [comment]
Seems to be a lot better now, I let it run for like 30 minutes and got no corruption. But I did get another error, not sure if it's related (happened after around 30 minutes, and I had commented out the DBCommit() commands from both apps):


```
GenCode :	EG_DATAWIDTH Data width error
SubCode :	1121 Datawidth error
FuncSym :	FieldPut
Severity :	ES_ERROR
Can Default :	True
Can Retry :	False
Can Substitute :	False
FileName :	C:\test\Wolfgang.DBF
Stack Trace :	
DBFNUMERICCOLUMN:PUTVALUE (Line: 0)
DBFFPT:PUTVALUE (Line: 0)
COREDB:<>C__DISPLAYCLASS49_0:<FIELDPUT>B__0 (Line: 0)
COREDB:DO (Line: 0)
COREDB:FIELDPUT (Line: 0)
FIELDPUT (Line: 0)
START (Line: 12)
```

**Comment by RobertvanderHulst** [comment]
Chris,
This is a logical error in the test.
You are writing values > 9999 to the POSFORO field defined as N,4,0

If you change that field to N,10,0 and also update the index expression to STR(POSFORO,10) then the Datawidth error should not appear again (at least for several hours until your numbers get too big again).

**Comment by cpyrgas** [comment]
Oh, that's a good point :)
Looking very good so far, have let it run for a couple hours and get no errors. But I will also try some variations of the code to make sure...

**Comment by cpyrgas** [comment]
There are some tests failing, not sure if it's because of this fix, but it sounds likely. For example this one:

```
Description :	Value cannot be null.
Parameter name: source
Subsystem :	DBFCDX
GenCode :	EG_CORRUPTION Corruption detected
SubCode :	1002 Invalid skipping number
FuncSym :	DbSkip
Severity :	ES_ERROR
Can Default :	True
Can Retry :	False
Can Substitute :	False
FileName :	c:\test\abcd.DBF
Stack Trace :	
 ARRAY:COPY (Line: 0)
 CDXLEAFPAGE:_EXPANDKEYS (Line: 0)
 CDXLEAFPAGE:GETKEY (Line: 0)
 CDXPAGENODE:GET_KEYBYTES (Line: 0)
 CDXTAG:_SAVECURRENTRECORD (Line: 0)
 CDXTAG:_LOCATEFIRST (Line: 0)
 CDXTAG:SKIPRAW (Line: 0)
 CDXTAG:SKIPRAW (Line: 0)
 DBFCDX:SKIPRAW (Line: 0)
 DBF:SKIP (Line: 0)
 COREDB:DO (Line: 0)
 COREDB:SKIP (Line: 0)
 DBSKIP (Line: 0)
 START (Line: 11)

```



```
// taken from FieldGet_After_Skip_zero() test in the runtime suite
// https://github.com/X-Sharp/XSharpPublic/issues/698
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	RddSetDefault("DBFCDX")
	cDbf := "c:\test\abcd"
	CreateDatabase(cDbf , {{"FLD","N",5,0}} , {1,2} )
	DbCreateOrder("ORDER1", cDbf, "FLD")
	
	DbGoTop()
	DbSkip(-1)
	Assert.True( Bof() )
	Assert.True( FieldGet(1) == 1 )
	Assert.Equal( 1U , RecNo() )
	
	DbSkip(0)
	Assert.True( Bof() )
	Assert.True( FieldGet(1) == 1 )
	Assert.Equal( 1U , RecNo() )
	
	
	DbGoBottom()
	Assert.False( Eof() )
	Assert.True( FieldGet(1) == 2 )
	Assert.Equal( 2U , RecNo() )
	
	DbSkip(+1)
	Assert.True( Eof() )
	Assert.True( FieldGet(1) == 0 )
	Assert.Equal( 3U , RecNo() )
	
	DbSkip(0)
	Assert.True( Eof() )
	Assert.True( FieldGet(1) == 0 )
	Assert.Equal( 3U , RecNo() )
	
	DbSkip(+1)
	Assert.True( Eof() )
	Assert.True( FieldGet(1) == 0 )
	Assert.Equal( 3U , RecNo() )
	
	Assert.True( Eof() )
	
	DbCloseArea()
	
FUNCTION CreateDatabase(cFileName AS STRING, aFields AS ARRAY) AS VOID
	CreateDatabase(cFileName, aFields , {})
FUNCTION CreateDatabase(cFileName AS STRING, aFields AS ARRAY, aValues AS ARRAY) AS VOID
	IF File(cFileName + IndexExt())
		FErase ( FPathName() )
	ENDIF
	IF File(cFileName + ".fpt")
		FErase ( FPathName() )
	ENDIF
	IF File ( cFileName + ".dbt" )
		FErase ( FPathName() )
	ENDIF
	DbCreate( cFileName , aFields)
	IF ALen(aValues) == 0
		RETURN
	END IF
	DbUseArea(,,cFileName)
	FOR LOCAL i := 1 AS DWORD UPTO ALen ( aValues )
		DbAppend()
		FieldPut (1 , aValues[i])
	NEXT
	DbGoTop()
RETURN

CLASS Assert
	STATIC METHOD @@True(l AS LOGIC) AS VOID
		IF .not. l
			? "failed"
		ENDIF
	RETURN
	STATIC METHOD @@False(l AS LOGIC) AS VOID
		IF l
			? "failed"
		ENDIF
	RETURN
	STATIC METHOD @@Equal(u1 AS USUAL, u2 AS USUAL) AS VOID
		IF u1 != u2
			? "failed"
		ENDIF
	RETURN
END CLASS
```

**Comment by cpyrgas** [comment]
This is fixed now, but I'm seeing a couple others:

- From DBError_test():

```

FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	
	RddSetDefault("DBFCDX")
	
	cDbf := "c:\test\test.dbf"
	// FErase(cDbf + ".cdx")
	
	DbCreate( cDbf , {{"CFIELD" , "C" , 10 , 0 }})
	DbUseArea(,,cDbf,,TRUE)
	DbAppend() 
	DbUnLock() 
	TRY
		? FieldPut ( 1 , "ABC") // record not locked
	CATCH e AS XSharp.Error
		? e:Message
		? e:GenCodeText
		? e:SubCodeText // check if this displays correctly
		? e:OSCodeText
		? e:ToString() // exception here
	FINALLY
		DbCloseArea()
	END TRY
RETURN

```

This results to

A. A HANDLED exception on DBUseArea():

```
XSharp.Error
Variable does not exist

Callstack : 
static __Usual XSharp.MemVar._Get(System.String cName)() 
static __Usual XSharp.RT.Functions.__MemVarGet(System.String cName)() 
Object XSharp.MacroCompiler.ObjectMacro.MacroCodeblock.EvalBlock(System.Object[] args)() 
XSharp._Codeblock.__Usual XSharp._Codeblock.Eval(XSharp.__Usual[] args)() 
Object XSharp.Codeblock.EvalBlock(System.Object[] args)() 
XSharp.RDD.DBFCDX.Object XSharp.RDD.Workarea.EvalBlock(XSharp.ICodeblock oBlock)() 
XSharp.RDD.DBFCDX.Object XSharp.RDD.DBF.EvalBlock(XSharp.ICodeblock cbBlock)() 
XSharp.RDD.CDX.CdxTag.Boolean XSharp.RDD.CDX.CdxTag.EvaluateExpressions()() 
XSharp.RDD.CDX.CdxTag.Boolean XSharp.RDD.CDX.CdxTag.Open()() 
XSharp.RDD.CDX.CdxTag.System.Void XSharp.RDD.CDX.CdxTag..ctor(XSharp.RDD.CDX.CdxOrderBag oBag, System.Int32 nPage, System.String cName)() 
XSharp.RDD.CDX.CdxTagList.List`1 XSharp.RDD.CDX.CdxTagList.ReadTags()() 
Boolean XSharp.RDD.CDX.CdxOrderBag.Open(XSharp.RDD.Support.DbOrderInfo info)() 
XSharp.RDD.CDX.CdxOrderBagList.Boolean XSharp.RDD.CDX.CdxOrderBagList.Add(XSharp.RDD.Support.DbOrderInfo info, System.Boolean lStructural)() 
XSharp.RDD.DBFCDX.System.Void XSharp.RDD.DBFCDX.OpenProductionIndex(XSharp.RDD.Support.DbOpenInfo info)() 
XSharp.RDD.DBFCDX.Boolean XSharp.RDD.DBFCDX.Open(XSharp.RDD.Support.DbOpenInfo info)() 
Boolean XSharp.CoreDb+<>c__DisplayClass114_0.<UseArea>b__0()() 
static Object XSharp.CoreDb.Do(System.Func`1[System.Object] action)() 
static Boolean XSharp.CoreDb.UseArea(System.Boolean lNew, System.Type rddType, System.String cName, System.String cAlias, System.Boolean lShare, System.Boolean lReadOnly)() 
Boolean XSharp.CoreDb+<>c__DisplayClass112_0.<UseArea>b__0()() 
static Object XSharp.CoreDb.Do(System.Func`1[System.Object] action)() 
static Boolean XSharp.CoreDb.UseArea(System.Boolean lNew, XSharp._RddList rddList, System.String cName, System.String cAlias, System.Boolean lShare, System.Boolean lReadOnly)() 
static Boolean XSharp.RT.Functions.DbUseArea(XSharp.__Usual[] Xs$Args)() 
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  10

```

B. An unhandled exception in DBAppend():

```
System.NullReferenceException
Object reference not set to an instance of an object.

Callstack : 
XSharp.RDD.CDX.CdxTag.Boolean XSharp.RDD.CDX.CdxTag._saveCurrentKey(System.Int32 rcno, XSharp.RDD.RddKeyData oData)() 
XSharp.RDD.CDX.CdxTag.Boolean XSharp.RDD.CDX.CdxTag._keyUpdate(System.Int32 recordNo, System.Boolean lNewRecord)() 
Boolean XSharp.RDD.CDX.CdxTag.GoCold()() 
Boolean XSharp.RDD.CDX.CdxOrderBag.GoCold()() 
Boolean XSharp.RDD.CDX.CdxOrderBagList.GoCold()() 
XSharp.RDD.DBFCDX.Boolean XSharp.RDD.DBFCDX.GoCold()() 
XSharp.RDD.DBFCDX.Boolean XSharp.RDD.DBF.Append(System.Boolean lReleaseLock)() 
Boolean XSharp.CoreDb+<>c__DisplayClass18_0.<Append>b__0()() 
static Object XSharp.CoreDb.Do(System.Func`1[System.Object] action)() 
static Boolean XSharp.CoreDb.Append(System.Boolean lReleaseLocks)() 
static Boolean XSharp.RT.Functions.DbAppend(XSharp.__Usual[] Xs$Args)() 
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  11

```

**Comment by cpyrgas** [comment]
Also, taken from C795:

in VFP dialect only:

```
FUNCTION Start() AS VOID
LOCAL cFileName AS STRING
cFileName := "testvfp"
DbCreate(cFileName , {{"FLD","N",5,0}})
DbUseArea(,,cFileName)
DbAppend()
DbAppend()
DbGoTop()

DbEval({|| EvalFunc( RecNo())} )

FUNCTION EvalFunc(n AS DWORD) AS VOID
? n

```

this results to a dialog:


```

---------------------------
ERROR
---------------------------
Description :	Unknown Error occurred

Subsystem :	BASE

GenCode :	EG_EXCEPTION Exception raised by CLR or external code

FuncSym :	DbEval

Severity :	ES_ERROR

Can Default :	False

Can Retry :	False

Can Substitute :	False

Stack Trace :	

   at XSharp.RT.Functions._DbThrowErrorOnFailure(String funcName, Boolean resultToCheck)

   at XSharp.RT.Functions.DbEval(__Usual[] Xs$Args)

   at fox.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\fox\Prg\fox.prg:line 13




---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by RobertvanderHulst** [comment]
Fixed. The original corruption issue has been solved. I have created a new issue for the DbEval problem
