### ISSUE TITLE
When DBF field name has same name as built-in function then compilation error occurs

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#64]
When a DBF Index expression has a field with the same name as a built in function or enum then an error occurs when compiling the index expression.

For example:

 
```

FUNCTION Start AS VOID STRICT
 LOCAL aStruct AS ARRAY
 TRY
 aStruct := {{"ASCII","C",10,0},{"SET","C",10,0}}
 DBCreate("Test",aStruct)
 DbUseArea(TRUE,,"Test")
 DBCreateIndex("test","ASCII+SET")
 CATCH e AS Exception
 ? e:Message
 END TRY
 Console.Read()
 RETURN

```

This generates the error message:

(1,10): error XM0222: <symbol group> is not a valid expression term

When the field is prefixed with _FIELD-> then it works as expected.

SET should be parsed as an undefined identifier, and should resolve to a call to global::XSharp.RT.Functions.__VarGet

The problem seems to be that there is a Set enum in the runtime as well as a Set() function.

**Comment by RobertvanderHulst** [comment]
The problem in this case is not that there is a function Set(). The macro compiler can distinguish the Set function from the SET field. The problem seems to be the fact that the Macro compiler also finds the XSharp.Set enum. I have fixed this for now, but maybe a better fix is needed.

**Comment by nvkokkalis** [comment]
There is still a problem when there is a function or type with the same name as a global. In this case the identifier never resolves to the global, as it should. I have fixed it, but not pushed it yet (will do some tests first).
