### ISSUE TITLE
Intellisense Crash in xh File

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#657]
Following happened when typing

iif(

inside a #command in dbcmd.xh

Also when using in VS "Add new Item->Code->Header", then a header1.vh file is being created, not a .xh one

```
System.NullReferenceException: Object reference not set to an instance of an object.
at XSharp.LanguageService.XSharpSearchLocation.GetUsings() in C:\XSharp\DevPublic\VisualStudio\LanguageService\Lookup\XSharpSearchLocation.cs:line 89
at XSharp.LanguageService.XSharpSearchLocation..ctor(XSourceMemberSymbol member, ITextSnapshot snapshot, Int32 lineNumber, Int32 position, String currentNs) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Lookup\XSharpSearchLocation.cs:line 55
at XSharp.LanguageService.CommandFilter.StartSignatureSession(Boolean comma, IXTypeSymbol type, String methodName) in C:\XSharp\DevPublic\VisualStudio\LanguageService\CommandFilter.cs:line 1252
at XSharp.LanguageService.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\XSharp\DevPublic\VisualStudio\LanguageService\CommandFilter.cs:line 647
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) 
--- End of stack trace from previous location where exception was thrown --- 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by RobertvanderHulst** [comment]
Was fixed in 75ea5b5f

**Comment by RobertvanderHulst** [comment]
In the next build I will improve the parser so it will always returns members, so there is always a valid "context" for the intellisense. If there are no entities then it will return a "Namespace" object.
Maybe I will also add members to the members combobox for `[AssemblyInfo]` attributes, for` #defines`  and for UDCs.
Does that make sense ?

**Comment by cpyrgas** [comment]
It makes sense of course, but only as long as it does not hurt performance! So if you are sure it will not have a noticeable negative impact..

**Comment by RobertvanderHulst** [comment]
I doubt that this will have a measurable performance impact. When we are colorizing the buffer we are already inspecting all the tokens in the buffer. At that time we are setting the color for the preprocessor items, so we can also create a list of these items (`#define, #command, #translate`) and then later add this to the list of "global" items in the parser. 
And the parser already knows how to parse attributes. It should not hurt to add a few extra members to the list. And there will never be many attributes. No more than 10-15 I expect.
The advantage of adding the `#defines` is that we can then also find them for QuickInfo, Code Completion, Goto Definition, Peek definition etc. 
I will treat the `#defines` for the members combobox as defines and fields, so I will only include them when the matching option on the intellisense page is enabled. But regardless of this option, they will then be added to the intellisense database.

Maybe I can also detect the header files  (`#include statements`) that are used by the project and include them "silently" in the intellisense database so that the `#defines` in included header files are also available for the same purpose

**Comment by cpyrgas** [comment]
AAAaahhh, that's what you meant with members combobox! Right, yeah it looks great!

**Comment by RobertvanderHulst** [comment]
The good thing is that when you use the TEST define in your code then the quick info will also show it and Goto Definition will also work. I "only" have to make sure that the define (and UDCs etc) are not found in other modules (I am adding this to the (Global Scope) I'll probably have to mark it as "Static" just like the STATIC GLOBALs. and STATIC FUNCTIONs.
An alternative would be to not persist these in the intellisense database.

**Comment by cpyrgas** [comment]
Yeah, that's the part that worried me about performance. What happens if there are defines in a #include statement, are those persisted and/or displayed as well? It could be thousands of defines and dozens of commands available this way..

Or even within the file itself, if it contains a large window, it could contain literally 100s of #defines.

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
The problem with intellisense is fixed, but when I tried to add a new include file, I got the error dialog below. Indeed, this folder contains only:

Header.png
Header.vstemplate

---------------------------
Microsoft Visual Studio
---------------------------
Could not find file 'C:\Users\cpc\AppData\Local\Microsoft\VisualStudio\15.0_e22d73ed\VTC\d2f2f174596257d9d6f57cfc7b58c653\~IC\ItemTemplates\Code\Header.zip\Header.xh'.
---------------------------
OK   
---------------------------

**Comment by cpyrgas** [comment]
The problem with adding a new .xh file still exists. Not worth delaying the build for that, though.
