### ISSUE TITLE
FieldGet() after EOF gives a runtime error 

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#698]
The following code gives a runtime error in X# - in VO it does not.

`
function Start() as void
            local aStruct                           as array
            local oDBServer                                 as DBServer
            local nI                                             as dword
            local cFileName                                 as string
            aStruct             := {}
            AAdd( aStruct, { "Field1", "N", 10, 0 } )
            AAdd( aStruct, { "Field2", "C", 10, 0 } )
            cFileName                    := "C:\temp\test.dbf"
            DbCreate( cFileName, aStruct, "DBFCDX", true, "TEST",, false )
            TEST->DbSetOrderCondition( ,,,,,,,,,,true )
            TEST->DbCreateOrder( "ORDER1",, "Str(FIELD1,8)", {|| Str( _FIELD->FIELD1,8 ) }, false )
            TEST->DbCreateOrder( "ORDER2",, "Upper(FIELD2)", {|| Upper( _FIELD->FIELD2 ) }, false )
            TEST->DbCloseArea()
            DebOut( "Created" )
            oDBServer                    := dbServer{ cFileName, true, false, "DBFCDX" }
            for nI := 1 upto 10
                        oDBServer:Append()
                        oDBServer:FieldPut( "Field1", nI )
                        oDBServer:FieldPut( "Field2", NTrim( nI ) )
                        oDBServer:Commit()
                        oDBServer:Unlock()
            next
            oDBServer:Close()
            oDBServer                    := dbServer{ cFileName, true, false, "DBFCDX" }
            oDBServer:SetOrder( "ORDER1" )
            oDBServer:GoBottom()
            System.Console.WriteLine( NTrim( oDBServer:FieldGet( #Field1 ) ) )
            oDBServer:Skip( 1 )
            System.Console.WriteLine( NTrim( oDBServer:FieldGet( #Field1 ) ) )
            oDBServer:Skip( 0 )
            System.Console.WriteLine( NTrim( oDBServer:FieldGet( #Field1 ) ) )
            oDBServer:Close()

return
`

**Comment by cpyrgas** [comment]
Oh, thank you very much for reporting this Wolfgang! This has been reported also by another developer and I've been trying to reproduce it in my machine for days now, without success. Looks like the Skip(0) call was the missing thing that makes the problem come to surface. Here's a simplified version of the repro sample:


```
FUNCTION Start() AS VOID
LOCAL aStruct AS ARRAY
LOCAL nI AS DWORD
LOCAL cFileName AS STRING

aStruct             := {}
cFileName                    := "C:\temp\test"
FErase(cFileName + ".cdx")

DbCreate( cFileName, {{ "FIELD1", "N", 4, 0 }}, "DBFCDX", TRUE)
DbCreateOrder( "ORDER1",, "FIELD1")

FOR nI := 1 UPTO 1
	DbAppend()
	FieldPut( 1 , nI )
NEXT

DbGoBottom()
? Eof() // false, OK
? FieldGet( 1 )

DbSkip( 1 )
? Eof() // true, OK
? FieldGet( 1 )

DbSkip( 0 )
? Eof() // false, wrong!
? FieldGet( 1 ) // exception

DbCloseArea()



Callstack : 
System.Void XSharp.RDD.DBF._dbfError(System.Exception ex, System.UInt32 iSubCode, System.UInt32 iGenCode, System.String strFunction, System.String strMessage, System.UInt32 iSeverity, System.Boolean lThrow)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg  :  1421
Object XSharp.RDD.DBF.GetValue(System.Int32 nFldPos)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg  :  1523
Object XSharp.RDD.DBFFPT.GetValue(System.Int32 nFldPos)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfFpt\DbfFpt.prg  :  291
XSharp.CoreDb+<>c__DisplayClass42_0.Boolean XSharp.CoreDb+<>c__DisplayClass42_0.<FieldGet>b__0()()   :  C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg  :  751
static Object XSharp.CoreDb.Do(System.Func`1[System.Object] action)()   :  C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg  :  234
static Boolean XSharp.CoreDb.FieldGet(System.UInt32 nPos, System.Object oRet)()   :  C:\xSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg  :  749
static Boolean XSharp.VoDb.FieldGet(System.UInt32 nPos, XSharp.__Usual uRet)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Vodb.prg  :  43
static __Usual XSharp.RT.Functions.FieldGet(XSharp.__Usual[] Xs$Args)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Db.prg  :  717
```

**Comment by cpyrgas** [comment]
There's also another issue, which probably boils down to the same thing. When already at Bof(), after doing a Skip(0), Bof now returns false:

```
FUNCTION Start() AS VOID
LOCAL cFileName AS STRING
cFileName := "C:\temp\test"
FErase(cFileName + ".cdx")

DbCreate( cFileName, {{ "FIELD1", "N", 4, 0 }}, "DBFCDX", TRUE)
DbCreateOrder( "ORDER1",, "FIELD1")

DbAppend()
FieldPut( 1 , 1 )

DbGoTop()
DbSkip(-1)
? Bof()         // TRUE, OK
? RecNo()       // 1, OK
? FieldGet( 1 ) // 1, OK

DbSkip(0)
? Bof()         // FALSE, wrong!
? RecNo()       // 1, OK
? FieldGet( 1 ) // 1, OK

DbCloseArea()

```

**Comment by RobertvanderHulst** [comment]
Fixed in commit 5e73bb62e97ec6820941aba01d19e34e19c78709

**Comment by cpyrgas** [comment]
Robert, there is no exception now anymore, but EoF() still returns FALSE after the Skip(0), while it was TRUE before this operation.

The small problem with BoF also still exists, but that's probably a different thing, will open a separate ticket for it.

**Comment by cpyrgas** [comment]
Also the original sample from Wolfgang still throws a runtime error. There must be another issue causing this which I did not catch in my sample, will look into it.

**Comment by cpyrgas** [comment]
Found it, there's still an exception when opening the file in shared mode. I am attaching below a newer sample which sums up the issues that still exist:

- In both SHARED and EXCLUSIVE mode, EoF() returns FALSE, after s Skip(0)
- In SHARED mode, FieldGet() throws an exception

Robert, please take your time, the update will be ready when it's ready.

```
FUNCTION Start() AS VOID
LOCAL nI AS DWORD
LOCAL cFileName AS STRING

cFileName                    := "C:\temp\test"
FErase(cFileName + ".cdx")

DbCreate( cFileName, {{ "FIELD1", "N", 4, 0 }}, "DBFCDX", TRUE)
DbCreateOrder( "ORDER1",, "FIELD1")

FOR nI := 1 UPTO 1
	DbAppend()
	FieldPut( 1 , nI )
NEXT
DbCloseArea()

? "exclusive mode:"
DbUseArea(TRUE,"DBFCDX",cFileName,,FALSE)
DbGoBottom()
? Eof() // false, OK
? FieldGet( 1 ) // 1, OK

DbSkip( 1 )
? Eof() // true, OK
? FieldGet( 1 ) // 0, OK

DbSkip( 0 )
? Eof() // false, wrong! <-------------------
? FieldGet( 1 ) // 0, OK
DbCloseArea()

? "shared mode:"
DbUseArea(TRUE,"DBFCDX",cFileName,,TRUE)
DbGoBottom()
? Eof() // false, OK
? FieldGet( 1 ) // 1, OK

DbSkip( 1 )
? Eof() // true, OK
? FieldGet( 1 ) // 0, OK

DbSkip( 0 )
? Eof() // false, wrong! <-------------------
? FieldGet( 1 ) // exception <-------------------
DbCloseArea()
```

**Comment by cpyrgas** [comment]
Confirmed fixed.
